### ISSUE TITLE
Wrong column name in example code

### ISSUE THREAD

**Issue by sfd99** [luisDVA/unheadr#1]
Hi Luis,  great, useful Pkg!.

In the code example:
  # put geographic regions in their own variable (matching them all by name)
    untangle2(primates2017,"Asia|Madagascar|Mainland   Africa|Neotropics",scientific_name,  family)
shouldn't it say, instead:
     Africa|Neotropics",scientific_name,  region) ?.

Thanks again!
SFd99
San Francisco

**Comment by luisDVA** [comment]
you're right, I've fixed it now. 
Good spotting, and thanks for the feedback.
