### ISSUE TITLE
Issue reading excel file

### ISSUE THREAD

**Issue by JauntyJJS** [luisDVA/unheadr#5]
Hi,

I tried to read this excel file below using annotate_mf_all but was unsuccessful.

[sample_excel.xlsx](https://github.com/luisDVA/unheadr/files/14421111/sample_excel.xlsx)

![image](https://github.com/luisDVA/unheadr/assets/9066508/a340ada0-0f48-4c43-964a-927b2f50dfcb)

Could you assist me in this as the file does contain a single sheet and it looks tabular ?

**Comment by luisDVA** [comment]
will look into this asap!

**Comment by luisDVA** [comment]
can you share the file again? I'm getting a 404 error

**Comment by JauntyJJS** [comment]
Ok sure.
[sample_excel.xlsx](https://github.com/luisDVA/unheadr/files/14587920/sample_excel.xlsx)

**Comment by JauntyJJS** [comment]
It is actually the same file as 

https://raw.githubusercontent.com/JauntyJJS/jaunty-blogdown/main/content/blog/2024-02-15-Tackling-Formatted-Cell-Data/sample_excel.xlsx

**Comment by luisDVA** [comment]
I've identified the problem. It is an assumption I made about the number of non-NA values across rows define rectangular data. In the particular case of your spreadsheet, having a variable with so many empty values at the 'end' of the table confuses the condition. I'll patch the functions but in the meantime you could simply move that last variable to get the function to work.

**Comment by JauntyJJS** [comment]
I see. Thank you for looking into this. 
Let me know when the function is able to take in a variable with many empty values at the start of the dataset.

**Comment by luisDVA** [comment]
closing. addressed this issue  in the latest release, now on CRAN.
your particular file had some cells beyond the data rectangle that had formatting even when empty, so the number of rows didn't match between the outputs of tidyxl and readxl. The funciton has better error messages for these cases.
